# Omakase Ruby styling for Rails
inherit_gem: { rubocop-rails-omakase: rubocop.yml }

# Disable all styling, spacing, and formatting cops
Layout:
  Enabled: false

Style:
  Enabled: false

Lint/DeprecatedClassMethods:
  Enabled: false
Lint/MissingCopEnableDirective:
  Enabled: false
Lint/Void:
  Enabled: false
Style/MethodCallWithArgsParentheses:
  Enabled: false
