name: CI

on:
  push:
    branches: [ main ]
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true

      - name: Install system deps
        run: |
          sudo apt-get update
          sudo apt-get install -y libvips sqlite3

      - name: Setup
        run: bin/setup --skip-server

      - name: Style: Ruby
        run: bin/rubocop

      - name: Security: Gem audit
        run: bin/bundler-audit

      - name: Security: Importmap vulnerability audit
        run: bin/importmap audit

      - name: Security: Brakeman code analysis
        run: bin/brakeman --quiet --no-pager --exit-on-warn --exit-on-error

      - name: Tests: Rails
        run: bin/rails test

      - name: Tests: Seeds
        run: env RAILS_ENV=test bin/rails db:seed:replant
